server:
  # 服务端口号
  port: 9092

spring:
  application:
    # 服务名，即serviceId
    name: service-feign
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      # 安全认证的服务注册中心地址
      defaultZone: http://${eureka.instance.hostname}:9090/eureka

