## spring cloud config [server]

server:
  port: 9104

# spring config

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
        # 自己在github 上创建一个文件
          uri: https://github.com/SoftCancer/SpringcloudConfig.git
#          uri: https://github.com/SoftCancer/SpringcloudConfig
          search-paths: server
          username:
          password:
      label: master

# spring cloud eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9090/eureka/