server:
  port: 9107
# spring config
spring:
  application:
    ####注册中心应用名称
    name: zipkin-server
  main:
    allow-bean-definition-overriding: true
## spring cloud eureka 注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9090/eureka/
